# Generated by Django 4.0.5 on 2022-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tech',
            field=models.ManyToManyField(blank=True, null=True, to='users.tech'),
        ),
    ]
