# Generated by Django 4.0.5 on 2022-07-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tech_user_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='test', max_length=60, null=True),
        ),
    ]
