# Generated by Django 4.0.6 on 2022-08-12 09:56

import birthday.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=birthday.fields.BirthdayField(blank=True, default=datetime.datetime(2022, 8, 12, 15, 26, 24, 621513)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader'), ('Manager', 'Manager'), ('Developer', 'Developer'), ('HR', 'HR'), ('Junior Developer', 'Junior Developer'), ('Trainee', 'Trainee')], default='test', max_length=60, null=True),
        ),
    ]
