# Generated by Django 4.0.6 on 2022-09-07 05:53

import birthday.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_dob_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=birthday.fields.BirthdayField(blank=True, default=datetime.datetime(2022, 9, 7, 11, 23, 53, 289086)),
        ),
    ]
