# Generated by Django 4.0.6 on 2022-08-12 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_project_project_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_assign',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_controll_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_controll_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, to='projects.tasks'),
        ),
    ]
