# Generated by Django 4.0.6 on 2022-08-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
