# Generated by Django 4.0.6 on 2022-08-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_budget_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='estimeted',
            new_name='estimeted_budget',
        ),
    ]
