# Generated by Django 4.0.6 on 2022-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_estimeted_budget_estimeted_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='estimeted_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
