# Generated by Django 4.0.6 on 2022-08-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_budget_estimeted_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='delete',
            new_name='on_delete',
        ),
    ]
