# Generated by Django 4.0.6 on 2022-08-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_delete_tasks_on_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='delete',
            new_name='on_delete',
        ),
    ]
