# Generated by Django 4.0.6 on 2022-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to='projects.tasks'),
        ),
    ]
