# Generated by Django 4.0.6 on 2022-09-07 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_alter_project_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_assign',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
