# Generated by Django 4.0.6 on 2022-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_holiday_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
