# Generated by Django 4.0.6 on 2022-09-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
