# Generated by Django 4.0.6 on 2022-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='increament',
            field=models.FloatField(default=0),
        ),
    ]
