# Generated by Django 4.0.6 on 2022-09-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_mokshit', '0003_salary_apply_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.FloatField(default=0)),
                ('hra', models.FloatField(default=0)),
                ('increament', models.FloatField(default=0)),
                ('deduction', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_action_by', to=settings.AUTH_USER_MODEL)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='admin_mokshit.salary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
