# Generated by Django 4.0.6 on 2022-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0005_alter_payslip_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='month',
            field=models.CharField(default='g', max_length=100),
        ),
    ]
