# Generated by Django 4.0.6 on 2022-09-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0007_alter_payslip_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.DateField(),
        ),
    ]
