# Generated by Django 4.0.6 on 2022-09-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0008_alter_payslip_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='month',
            new_name='month_year',
        ),
    ]
