# Generated by Django 4.0.6 on 2022-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0010_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
