# Generated by Django 4.0.6 on 2022-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0011_contacts_city_contacts_landmark_contacts_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='embed_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
