# Generated by Django 4.0.6 on 2022-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0013_site_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('quotes', models.TextField()),
                ('image', models.ImageField(blank=True, default='static/client/default.jpg', null=True, upload_to='static/client')),
            ],
        ),
    ]
