# Generated by Django 4.0.6 on 2022-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0014_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_client', models.IntegerField()),
                ('total_project', models.IntegerField()),
                ('hours_support', models.IntegerField()),
                ('hard_worker', models.IntegerField()),
            ],
        ),
    ]
