# Generated by Django 4.0.6 on 2022-09-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_project_assign_and_more'),
        ('admin_mokshit', '0015_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img_title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='static/portfolio/default.jpg', null=True, upload_to='static/portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
