# Generated by Django 4.0.6 on 2022-09-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mokshit', '0016_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.TextField()),
            ],
        ),
    ]
