# Generated by Django 4.0.5 on 2022-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leave_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.BooleanField(default=False),
        ),
    ]
