# Generated by Django 4.0.5 on 2022-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leave_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
