# Generated by Django 4.0.6 on 2022-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_alter_leave_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='test', max_length=60, null=True),
        ),
    ]
