# Generated by Django 4.0.6 on 2022-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
