# Generated by Django 4.0.6 on 2022-08-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_leave_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='approve_at',
            new_name='on_delete',
        ),
    ]
