# Generated by Django 4.0.6 on 2022-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokshitsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
