# Generated by Django 4.0.6 on 2022-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokshitsite', '0002_contactlist_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='Message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
